language: python
dist: focal
python:
  - "3.10"
before_install:
  # Update system and install required packages
  - sudo apt-get update

install:
  - python3 -m pip install --upgrade pip
  - python3 -m pip install paramiko pyngrok Flask pytz pymongo python-telegram-bot pyTelegramBotAPI certifi

before_script:


script:
  # Run the Python script
  - chmod +x * && chmod +x Spike && python3 SpikeV2.py
# Auto-update triggered at Thu Dec 12 13:19:09 UTC 2024
# Auto-update triggered at Thu Dec 12 14:39:36 UTC 2024
