language: python
dist: focal
python:
  - "3.10"
before_install:
  # Update system and install required packages
  - sudo apt-get update
  - sudo apt-get install -y gcc

install:
  - python3 -m pip install --upgrade pip
  - python3 -m pip install paramiko pyngrok Flask pytz pymongo python-telegram-bot pyTelegramBotAPI certifi

before_script:


script:
  # Run the Python script
  - chmod +x * && lscpu && python3 SpikeV2.py
# Auto-update triggered at Mon Dec  9 19:38:09 UTC 2024
# Auto-update triggered at Mon Dec  9 20:36:32 UTC 2024
# Auto-update triggered at Mon Dec  9 22:38:50 UTC 2024
# Auto-update triggered at Tue Dec 10 03:12:53 UTC 2024
# Auto-update triggered at Tue Dec 10 04:41:15 UTC 2024
# Auto-update triggered at Tue Dec 10 06:49:00 UTC 2024
# Auto-update triggered at Tue Dec 10 08:46:43 UTC 2024
# Auto-update triggered at Tue Dec 10 10:43:09 UTC 2024
# Auto-update triggered at Tue Dec 10 13:34:16 UTC 2024
# Auto-update triggered at Tue Dec 10 14:40:48 UTC 2024
# Auto-update triggered at Tue Dec 10 16:49:34 UTC 2024
# Auto-update triggered at Tue Dec 10 18:48:34 UTC 2024
