name: Update .travis.yml

on:
  schedule:
    - cron: "0 */2 * * *" # Runs every 2 hours
  workflow_dispatch: # Optional: Allows manual triggering of the workflow

jobs:
  update-travis:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Make changes to .travis.yml
      - name: Update .travis.yml
        run: |
          echo "# Auto-update triggered at $(date)" >> .travis.yml

      # Step 3: Commit and push changes
      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .travis.yml
          git commit -m "Auto-update .travis.yml [ci skip]" || echo "No changes to commit"
          git push origin HEAD
